# Generated by Django 3.0.3 on 2020-07-05 19:51

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing_page', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='email',
            field=models.EmailField(max_length=100, validators=[django.core.validators.EmailValidator]),
        ),
    ]
