branch-defaults:
  Prod:
    environment: django-env
    group_suffix: null
global:
  application_name: sapir-prod
  branch: null
  default_ec2_keyname: sapir-prod
  default_platform: Python 3.6
  default_region: eu-central-1
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: eb-cli
  repository: null
  sc: git
  workspace_type: Application
